[package]
name = "sam-client"
version = "0.1.0"
edition = "2021"
description = "Create clients that can communicate through a SAM server."
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sam-common = { workspace = true }

libsignal-protocol = { workspace = true }
libsignal-core = { workspace = true }
derive_more = { workspace = true, features = ["display", "error", "from"] }
async-trait = { workspace = true }
uuid = { workspace = true, features = ["v4", "fast-rng", "macro-diagnostics"] }
base64 = { workspace = true }
bon = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }
futures-util = { workspace = true, features = ["sink"] }
prost = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
