[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
description = "Test utilities"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sam-server = { workspace = true }
sam-common = { workspace = true }
axum = { workspace = true }
axum-test = { workspace = true }
rand = { workspace = true }
libsignal-protocol = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
