package sam_message;


enum EnvelopeType {
  SIGNAL_MESSAGE = 1;
  PRE_KEY_SIGNAL_MESSAGE = 2;
  SENDER_KEY_MESSAGE = 3;
  PLAINTEXT_CONTENT = 4;
}

message ClientEnvelope {
  required EnvelopeType type = 1;
  map<uint32, bytes> content = 2;
  required bytes  destination_account_id = 3;
  required bytes  source_account_id = 4;
  required uint32 source_device_id  = 5;
}

message ServerEnvelope {
  required EnvelopeType type = 1;
  required bytes content = 2;
  required bytes  destination_account_id = 3;
  required uint32 destination_device_id  = 4;
  required bytes  source_account_id = 5;
  required uint32 source_device_id  = 6;
  required bytes id = 7;
}

enum MessageType {
  MESSAGE = 1;
  ACK = 2;
  STATUS = 3;
}

message DeviceList {
  repeated uint32 ids = 1;
}

enum StatusCode {
  NEEDS_SYNC = 1;
  NOT_ENCRYPTED_FOR_ALL_DEVICES=2;
  ENCRYPTED_FOR_EXTRA_DEVICES=3;
}

message Status {
  required StatusCode code = 1;
  optional DeviceList device_ids = 2;
}

message ClientMessage {
  required MessageType type = 1;
  required bytes id = 2;
  optional ClientEnvelope message = 3;
}

message ServerMessage {
  required bytes id = 1;
  required MessageType type = 2;

  oneof content {
    ServerEnvelope message = 3;
    Status status = 4;
  };
}
