package sam_message;

enum SamMessageType {
  SIGNAL_MESSAGE = 1;
  PRE_KEY_SIGNAL_MESSAGE = 2;
  SENDER_KEY_MESSAGE = 3;
  PLAINTEXT_CONTENT  = 4;
}

message SamMessage {
  required SamMessageType type = 1;
  required bytes  destination_account_id = 2;
  required uint32 destination_device_id = 3;
  required bytes  content = 4;
}

message ClientEnvelope {
  repeated SamMessage messages = 1;
}

message ServerEnvelope {
  required SamMessageType type = 1;
  required bytes  content = 2;
  required bytes  destination_account_id = 3;
  required uint32 destination_device_id  = 4;
  required bytes  source_account_id = 5;
  required uint32 source_device_id  = 6;
  required bytes  id = 7;
}



message DeviceList {
  required bytes  account_id = 1;
  repeated uint32 device_ids = 2;
}

enum ClientMessageType {
  CLIENT_MESSAGE = 1;
  CLIENT_ACK = 2;
}

message ClientMessage {
  required ClientMessageType type = 1;
  required bytes id = 2;
  optional ClientEnvelope message = 3;
}

enum ServerMessageType {
  SERVER_MESSAGE = 1;
  SERVER_ACK = 2;

  NEEDS_SYNC = 4;
  EMPTY_MESSAGE = 5;
  NOT_ENCRYPTED_FOR_ALL_DEVICES = 6;
  ENCRYPTED_FOR_EXTRA_MESSAGES = 7;
}


message MissingDevicesError {
  repeated DeviceList device_lists = 1;
}

message ExtraDevicesStatus {
  repeated DeviceList device_lists = 1;
}

message ServerMessage {
  required bytes id = 1;
  required ServerMessageType type = 2;

  oneof content {
    ServerEnvelope server_envelope = 3;
    MissingDevicesError missing_devices = 4;
    ExtraDevicesStatus extra_devices = 5;
  };
}
