[package]
name = "sam-server"
version = "0.1.0"
edition = "2021"
description = "A basic SAM server and the components needed to create your own."
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
tokio-console = ["console-subscriber"]


[dependencies]
bon = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
argon2 = { workspace = true }
clap = { workspace = true, features = ["string"] }
libsignal-protocol = { workspace = true }
derive_more = { workspace = true, features = ["display", "error", "from"] }
sam-common = { workspace = true }
sam-net = { workspace = true }
tokio = { workspace = true, features = ["full"] }
futures-util = { workspace = true, features = ["sink"] }
async-trait = { workspace = true }
prost = { workspace = true }
axum = { workspace = true, features = ["ws", "macros"] }
axum-extra = { workspace = true, features = ["typed-header"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
env_logger = { workspace = true }
log = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rustls-pemfile = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid", "runtime-tokio"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tikv-jemallocator = { workspace = true }
tracing = { workspace = true }
console-subscriber = { workspace = true, optional = true }

[dev-dependencies]
sam-test-utils = { workspace = true }
axum-test = { workspace = true }
tokio-tungstenite = { workspace = true }
maplit = { workspace = true }
rstest = { workspace = true }
uuid = { workspace = true }
