[package]
name = "sam-e2e-tests"
version = "0.1.0"
edition = "2021"
description = "End-to-end tests for SAM"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sam-common = { workspace = true }
sam-client = { workspace = true }
sam-server = { workspace = true }
test-utils = { path = "../test_utils" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand = { workspace = true }
libsignal-protocol = { workspace = true }
env_logger = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
