[package]
name = "sam-e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
sam-common = { path = "../common" }
sam-client = { path = "../client" }
sam-server = { path = "../server"}
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
