[package]
name = "sam-common"
version = "0.1.0"
edition = "2021"
description = "Common dependencies of SAM client and server."
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
base64 = { workspace = true }
derive_more = { workspace = true, features = [
  "display",
  "error",
  "from",
  "into",
] }
prost = { workspace = true }
libsignal-protocol = { workspace = true }
tokio = { workspace = true, features = ["full"] }
futures-util = { workspace = true, features = ["sink"] }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["base64"] }
uuid = { workspace = true, features = ["serde", "v4"] }
bon = { workspace = true }
rand = { workspace = true }
axum = { workspace = true }
log = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rustls-pemfile = { workspace = true }
bincode = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
