name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:    
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Run fmt
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: ./.github/actiosns/setup

    - name: Run Clippy
      run: DATABASE_URL=${{ secrets.DATABASE_URL_CLIENT }} cargo clippy --all-targets --all-features -- -D warnings
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Run Test
      run: DATABASE_URL=${{ secrets.DATABASE_URL_CLIENT }} cargo test --all 
