name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  format:
    steps:
    - name: Run fmt
      run: cargo fmt --all -- --check
    concurrency:
      group: check
  clippy:
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      group: check
  test:
    - name: Run Test
      run: cargo test --all
      group: check
